# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continous integration

on:
  pull_request:
    branches: [ develop ]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: https://registry.npmjs.org
    - name: Install packages
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: Running tests
      run: |
        npm run test:cov
        npm run test:cov:clover
    - name: Report coverage
      if: always()
      uses: slavcodev/coverage-monitor-action@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clover_file: coverage/clover.xml
        threshold_alert: 75
        threshold_warning: 90
        comment_mode: update
    - name: Save Code Linting Report JSON
      if: always()
      run: npm run lint:report
    - name: Annotate Code Linting Results
      if: always()
      uses: ataylorme/eslint-annotate-action@1.0.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "eslint_report.json"
